-- ============================================================================
-- INTELLIGENZ 2K26 - SUPABASE POSTGRESQL DATABASE SETUP SCRIPT
-- ============================================================================
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard)
-- ============================================================================

-- 1. Create registrations table
CREATE TABLE IF NOT EXISTS public.registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TEXT,
  pass_id TEXT,
  name TEXT,
  email TEXT,
  mobile TEXT,
  reg_no TEXT,
  gender TEXT,
  college TEXT,
  dept TEXT,
  district TEXT,
  pincode TEXT,
  selected_events TEXT,
  referred TEXT,
  referral_source TEXT,
  referral_dept TEXT,
  utr_no TEXT,
  payment_proof TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS) and grant Anonymous public read/write access
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert" ON public.registrations;
CREATE POLICY "Allow public insert" ON public.registrations 
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public select" ON public.registrations;
CREATE POLICY "Allow public select" ON public.registrations 
  FOR SELECT USING (true);

GRANT ALL ON public.registrations TO anon;
GRANT ALL ON public.registrations TO authenticated;
GRANT ALL ON public.registrations TO service_role;

-- 3. Create Public Storage Bucket for Payment Screenshots
INSERT INTO storage.buckets (id, name, public) 
VALUES ('payment-proofs', 'payment-proofs', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Read Access" ON storage.objects;
CREATE POLICY "Public Read Access" ON storage.objects 
  FOR SELECT USING (bucket_id = 'payment-proofs');

DROP POLICY IF EXISTS "Public Upload Access" ON storage.objects;
CREATE POLICY "Public Upload Access" ON storage.objects 
  FOR INSERT WITH CHECK (bucket_id = 'payment-proofs');
